# use this image as your build container to collect the conda dependencies

## on your development machine
#docker run -d -p 5000:5000 --name registry registry:2
#docker buildx build --push --platform linux/amd64,linux/arm64 -t host.docker.internal:5000/hi-outdoor --output=type=image,push=true,registry.insecure=true .
#
#docker run --platform=linux/amd64 -it --rm --entrypoint /bin/bash localhost:5000/hi-outdoor
#(base) mambauser@a6c4e36ba289:/moveapps-python-sdk$ micromamba install python=3.9 qgis pluggy movingpandas python-dotenv scipy -c conda-forge
#(base) mambauser@a6c4e36ba289:/moveapps-python-sdk$ micromamba env export > environment-linux.amd64.yml
#(base) mambauser@a6c4e36ba289:/moveapps-python-sdk$ cat environment-linux.amd64.yml
## copy the output to your app repository

FROM mambaorg/micromamba:1.2.0-bullseye-slim
LABEL org.opencontainers.image.authors="us@couchbits.com"
LABEL org.opencontainers.image.vendor="couchbits GmbH"

# the app location
ENV PROJECT_DIR /moveapps-python-sdk
WORKDIR $PROJECT_DIR

# the OS depedencies
USER root
RUN chown -R $MAMBA_USER:$MAMBA_USER $PROJECT_DIR
RUN apt-get update \
    # fix for: `ImportError: libGL.so.1: cannot open shared object file: No such file or directory`
    && apt-get install ffmpeg libsm6 libxext6  -y

USER $MAMBA_USER
# the conda dependencies
COPY --chown=$MAMBA_USER:$MAMBA_USER environment-moveapps-arm64.yml ./environment.yml
#RUN micromamba install -y -n base -f ./environment.yml && \
#    micromamba clean --all --yes

COPY --chown=$MAMBA_USER:$MAMBA_USER sdk.py ./
COPY --chown=$MAMBA_USER:$MAMBA_USER sdk/ ./sdk/
COPY --chown=$MAMBA_USER:$MAMBA_USER resources/ ./resources/
COPY --chown=$MAMBA_USER:$MAMBA_USER tests/ ./tests/
COPY --chown=$MAMBA_USER:$MAMBA_USER app/ ./app/
